### ISSUE TITLE
Setting the Badge to an ImageView causes Crash

### ISSUE THREAD

**Issue by invizorys** [volders/Badger#16]
I try to set the badge to an ImageView
`CountBadge.Factory circleFactory = new CountBadge.Factory(getActivity(), BadgeShape.circle(.5f, Gravity.END | Gravity.TOP));
Badger.sett(binding.ivPolice, circleFactory).setCount(2);`

But I get the Crash:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
                                                                  at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:112)
                                                                  at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:94)
                                                                  at berlin.volders.badger.Badger.sett(Badger.java:56)
                                                                  at berlin.volders.badger.Badger.sett(Badger.java:109)`

**Comment by tynn** [comment]
This could mean that the factory returns null, but more likely your `ImageView` does not have a `Drawable` set. You should make sure this is done, since `Badger` operates on drawables only.
