### ISSUE TITLE
NullPointException for MenuItem in BottomNavigationView in support library

### ISSUE THREAD

**Issue by UsherBaby** [volders/Badger#6]
Badger.sett(menuItem, badgeFactory);

exception message:
Drawable$ConstantState.newDrawable() on a null object

**Comment by tynn** [comment]
Please always provide a full stacktrace.

**Comment by mradzinski** [comment]
Same exception here.

```
Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference
                                                                          at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:961)
                                                                          at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1007)
                                                                          at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:133)
                                                                          at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:912)
                                                                          at android.support.v4.graphics.drawable.DrawableWrapperGingerbread.mutate(DrawableWrapperGingerbread.java:215)
                                                                          at android.support.design.internal.BottomNavigationItemView.setIcon(BottomNavigationItemView.java:222)
                                                                          at android.support.design.internal.BottomNavigationItemView.initialize(BottomNavigationItemView.java:99)
                                                                          at android.support.design.internal.BottomNavigationMenuView.updateMenuView(BottomNavigationMenuView.java:308)
                                                                          at android.support.design.internal.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:64)
                                                                          at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:292)
                                                                          at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1047)
                                                                          at android.support.v7.view.menu.MenuItemImpl.setIcon(MenuItemImpl.java:438)
                                                                          at android.support.design.widget.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:184)
                                                                          at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                          at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                          at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                          at android.support.design.internal.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:90)
                                                                          at android.view.View.performClick(View.java:4780)
                                                                          at android.view.View$PerformClick.run(View.java:19866)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by tynn** [comment]
Related https://code.google.com/p/android/issues/detail?id=191754

**Comment by tynn** [comment]
The issue should be gone now. Mutability is not fully implemented though.
